### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `4.10.2`, as well as all build dependencies to the latest stable versions.

- publish-plugin `0.10.0`
- spock-core `1.2-groovy-2.4`
- jacoco `0.8.2`

Also, it removes a deprecated line `buildToolsVersion '25.0.2'` - it causes a warning, since more recent versions of the Android Gradle plugin have a matching default version specified:

```
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
```

### CODE REVIEW

**Comment by friederbluemle** [comment]
Gradle `4.8.1` is now available. I amended my commit and updated this PR.

**Comment by friederbluemle** [comment]
Gradle `4.9` is now available. I amended my commit and updated this PR.

**Comment by friederbluemle** [comment]
Gradle `4.10` is now available. I amended my commit and updated this PR.

**Comment by lbalmaceda** [comment]
@friederbluemle I just see this PR. Thanks and sorry for the delay 😿 . Would you mind making some changes??

- Change targetSdk/compileSdk versions from `25` to `28`
- Change the jacoco release version to `0.8.2`
- Change Maven publish plugin to `0.10.0`
- On the `ReadmeTask` file, make it replace both `"compile"` and `"implementation"` lines + add a test case for this

**Comment by friederbluemle** [comment]
@lbalmaceda Sure thing, I updated everything to the latest versions. 👍 Can I make the `ReadmeTask` updates in a different PR? Also just for clarification: _Both_ `compile` and `implementation` lines should be updated to `implementation`, correct?

**Comment by lbalmaceda** [comment]
@friederbluemle sorry I just merged the other PR since I needed this ASAP. Thanks for the effort!

**Pull request closed without merging**
